-- Script para criar a tabela users no Supabase
-- Execute isto no SQL Editor do painel do Supabase (https://supabase.com/dashboard)

-- Criar a tabela users
CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text UNIQUE NOT NULL,
    password text NOT NULL,
    user_type text DEFAULT 'aluno',
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Índice para busca por email (se não existir)
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- Função para atualizar o campo updated_at automaticamente (se não existir)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger para atualizar o campo updated_at automaticamente (se não existir)
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Adicionando política de segurança (segurança por RLS - Row Level Security)
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;  -- Comentado para permitir operações sem autenticação

-- Permissões básicas para operações sem autenticação (apenas para desenvolvimento)
-- Quando usar autenticação, habilite o RLS e crie políticas adequadas

-- Opções alternativas para permitir operações com autenticação (descomentar quando implementar JWT)
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Usuários autenticados podem selecionar" ON users FOR SELECT TO authenticated USING (true);
-- CREATE POLICY "Usuários autenticados podem inserir" ON users FOR INSERT TO authenticated WITH CHECK (true);
-- CREATE POLICY "Usuários podem atualizar próprios dados" ON users FOR UPDATE TO authenticated USING (auth.uid() = id);