CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text UNIQUE NOT NULL,
    password text NOT NULL,
    user_type text DEFAULT 'aluno', -- aluno ou professor
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    telefone text,
    foto_perfil text,
    -- Campos aluno
    data_nascimento date,
    altura float,
    objetivo text,
    -- Campos professor
    especializacao text,
    cref text,
    descricao text,
    experiencia_anos int
);

-- Índice
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- Trigger para updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_users_updated_at ON users;

CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- ======================
-- TABELA TREINOS
-- ======================
CREATE TABLE IF NOT EXISTS treinos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo text NOT NULL,
    descricao text,
    nivel text,
    categoria text,
    data_criacao timestamp with time zone DEFAULT now(),
    data_atualizacao timestamp with time zone DEFAULT now(),
    criador_id bigint REFERENCES users(id) ON DELETE CASCADE,
    aluno_id bigint REFERENCES users(id) ON DELETE CASCADE,
    ativo boolean DEFAULT true,
    observacoes text
);

CREATE INDEX IF NOT EXISTS idx_treinos_criador ON treinos (criador_id);
CREATE INDEX IF NOT EXISTS idx_treinos_aluno ON treinos (aluno_id);


-- ======================
-- TABELA EXERCICIOS
-- ======================
CREATE TABLE IF NOT EXISTS exercicios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    descricao text,
    categoria text,
    dificuldade text,
    series int,
    repeticoes int,
    carga float,
    duracao int,
    observacoes text,
    treino_id bigint REFERENCES treinos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_exercicios_treino ON exercicios (treino_id);


-- ======================
-- TABELA DIETAS
-- ======================
CREATE TABLE IF NOT EXISTS dietas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo text NOT NULL,
    descricao text,
    tipo_dieta text,
    data_inicio date,
    data_fim date,
    criador_id bigint REFERENCES users(id) ON DELETE CASCADE,
    aluno_id bigint REFERENCES users(id) ON DELETE CASCADE,
    ativo boolean DEFAULT true,
    observacoes text
);

CREATE INDEX IF NOT EXISTS idx_dietas_criador ON dietas (criador_id);
CREATE INDEX IF NOT EXISTS idx_dietas_aluno ON dietas (aluno_id);


-- ======================
-- TABELA REFEICOES
-- ======================
CREATE TABLE IF NOT EXISTS refeicoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    descricao text,
    horario time,
    tipo text,
    observacoes text,
    dieta_id bigint REFERENCES dietas(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_refeicoes_dieta ON refeicoes (dieta_id);


-- ======================
-- TABELA INGREDIENTES
-- ======================
CREATE TABLE IF NOT EXISTS ingredientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    quantidade float,
    unidade_medida text,
    calorias float,
    proteinas float,
    carboidratos float,
    gorduras float,
    refeicao_id bigint REFERENCES refeicoes(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ingredientes_refeicao ON ingredientes (refeicao_id);


-- ======================
-- TABELA HISTÓRICO PESO
-- ======================
CREATE TABLE IF NOT EXISTS historico_peso (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id bigint REFERENCES users(id) ON DELETE CASCADE,
    peso float NOT NULL,
    data_registro timestamp with time zone DEFAULT now(),
    observacoes text
);

CREATE INDEX IF NOT EXISTS idx_historico_peso_aluno ON historico_peso (aluno_id);


-- ======================
-- TABELA CONVERSAS
-- ======================
CREATE TABLE IF NOT EXISTS conversas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id bigint REFERENCES users(id) ON DELETE CASCADE,
    professor_id bigint REFERENCES users(id) ON DELETE CASCADE,
    data_inicio timestamp with time zone DEFAULT now(),
    ultima_mensagem timestamp with time zone,
    status text DEFAULT 'ativa'
);

CREATE INDEX IF NOT EXISTS idx_conversas_aluno ON conversas (aluno_id);
CREATE INDEX IF NOT EXISTS idx_conversas_professor ON conversas (professor_id);


-- ======================
-- TABELA MENSAGENS
-- ======================
CREATE TABLE IF NOT EXISTS mensagens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversa_id bigint REFERENCES conversas(id) ON DELETE CASCADE,
    remetente_id bigint REFERENCES users(id) ON DELETE CASCADE,
    conteudo text NOT NULL,
    data_envio timestamp with time zone DEFAULT now(),
    lida boolean DEFAULT false,
    tipo_usuario text
);

CREATE INDEX IF NOT EXISTS idx_mensagens_conversa ON mensagens (conversa_id);
CREATE INDEX IF NOT EXISTS idx_mensagens_remetente ON mensagens (remetente_id);


-- ======================
-- INSERTS DE TESTE
-- ======================

INSERT INTO users (name, email, password, user_type, telefone, data_nascimento, altura, objetivo)
VALUES 
('João Silva', 'joao@example.com', '1234', 'aluno', '51999999999', '2000-05-12', 1.80, 'Hipertrofia'),
('Maria Souza', 'maria@example.com', '1234', 'aluno', '51988888888', '1998-11-22', 1.65, 'Emagrecimento');

INSERT INTO users (name, email, password, user_type, especializacao, cref, experiencia_anos, descricao)
VALUES
('Carlos Personal', 'carlos@example.com', '1234', 'professor', 'Musculação', '123456-G/RS', 7, 'Professor experiente em treinos avançados');


-- Criar treino
INSERT INTO treinos (titulo, descricao, nivel, categoria, criador_id, aluno_id)
VALUES ('Treino A', 'Treino de peito e tríceps', 'intermediário', 'peito', 3, 1);

-- Exercícios
INSERT INTO exercicios (nome, descricao, categoria, dificuldade, series, repeticoes, carga, treino_id)
VALUES
('Supino reto', 'Execução no banco reto', 'força', 'moderado', 4, 10, 60, 1),
('Tríceps pulley', 'Pulley alto', 'força', 'fácil', 3, 12, 25, 1);

-- Criar dieta
INSERT INTO dietas (titulo, descricao, tipo_dieta, data_inicio, criador_id, aluno_id)
VALUES ('Dieta Hipercalórica', 'Foco em ganho de massa', 'hipercalórica', '2025-01-01', 3, 1);

-- Refeição
INSERT INTO refeicoes (nome, tipo, dieta_id)
VALUES ('Café da manhã', 'café da manhã', 1);

-- Ingredientes
INSERT INTO ingredientes (nome, quantidade, unidade_medida, calorias, refeicao_id)
VALUES ('Aveia', 80, 'g', 300, 1);